name: provision

on: [push]

jobs:
  microk8s-rabbitmq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install microk8s using actions/microk8s-action
        uses: balchua/microk8s-actions@v0.3.0
        with:
          channel: '1.26/stable'
          addons: '["dns", "host-access", "hostpath-storage"]'

      - name: Access microk8s
        run: |
          echo "Check access to mikrok8s cluster"
          kubectl get nodes
      
      - name: Install RabbitMQ cluster operator
        run: |
          echo "Install RabbitMQ using our Helm chart with pinned version"
          helm dependency update rabbitmq/install
          helm upgrade -i rabbitmq-cluster-operator rabbitmq/install

          echo "Watch operator starting up - wrapped in until to prevent 'error: no matching resources found'"
          until kubectl wait --for=condition=Ready pod -l app.kubernetes.io/name=rabbitmq-cluster-operator,app.kubernetes.io/instance=rabbitmq-cluster-operator --namespace default --timeout=120s; do : ; done

      - name: Install RabbitMQ
        run: |
          echo "Install CRDs via Kustomize"
          kubectl apply -k rabbitmq

          echo "Watch RabbitMQ coming up"
          kubectl wait --for=condition=Ready pod -l app.kubernetes.io/name=hello-rabbit --namespace default --timeout=120s

      - name: Check if the RabbitMQ management UI is accessible
        run: |
          echo "Extract username and password for RabbitMQ management UI"
          username="$(kubectl get secret hello-rabbit-default-user -o jsonpath='{.data.username}' | base64 --decode)"
          password="$(kubectl get secret hello-rabbit-default-user -o jsonpath='{.data.password}' | base64 --decode)"

          echo "Create port forwarding to the management UI (in background using '&' at the end to not block the terminal session)"
          kubectl port-forward "service/hello-rabbit" 15672 &

          echo "Access the management UI via curl"
          curl -u$username:$password localhost:15672/api/overview
